run:
	go run main.go request.go
run_dbinfo:
	go run dbinfo/dbinfo.go
run_item:
	go run item/item.go
run_filter:
	go run filter/filter.go
run_filters:
	go run filters/filters.go
run_update:
	go run update/update.go
